version: "3"

services:
  db:
    image: postgres:13.2-alpine
    environment:
      - POSTGRES_USER=learn-drf
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=learn-drf
    ports:
      - 5434:5432

  app:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - db:db
    depends_on:
      - db
    volumes:
      - ./src:/app/src
    command: bash -c "python src/manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    env_file:
      - .env
